import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ModalProvider } from "@/components/modal/context/modalContext";
import Footer from "@/sections/root-layout/footer/footer";
import PreviewModal from "@/components/preview-image/preview-modal";
import { PreviewProvider } from "@/components/preview-image/context/preview-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ModalProvider>
          <PreviewProvider>
            <div className="flex min-h-screen flex-col">
              <PreviewModal />
              {children}
              <Footer />
            </div>
          </PreviewProvider>
        </ModalProvider>
      </body>
    </html>
  );
}
