import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ModalProvider } from "@/components/modal/context/modalContext";
import PreviewModal from "@/components/preview-image/preview-modal";
import { PreviewProvider } from "@/components/preview-image/context/preview-context";
import { ToastContainer } from "react-toastify";
import { SessionProvider } from "next-auth/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
          <ModalProvider>
            <PreviewProvider>
              <div className="flex min-h-screen bg-muted flex-col">
                <ToastContainer />
                <PreviewModal />
                {children}
              </div>
            </PreviewProvider>
          </ModalProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
