import PerfumesContainer from "@/sections/perfumes/perfumes-container";
import { Perfume } from "@/types/perfumes";
import React from "react";

const perfumes: Perfume[] = [
  {
    id: "1",
    available: true,
    brand: "Chanel",
    cant: 1,
    gender: "Femenino",
    liters: 1,
    name: "Chanel No. 5",
    perfumeType: "Eau de Parfum",
    price: 100,
    scents: ["Floral", "Aldehydic"],
  },
  {
    id: "2",
    available: true,
    brand: "Chanel",
    cant: 1,
    gender: "Femenino",
    liters: 1,
    name: "Chanel No. 5",
    perfumeType: "Eau de Parfum",
    price: 100,
    scents: ["Floral", "Aldehydic"],
  },
  {
    id: "3",
    available: true,
    brand: "Chanel",
    cant: 1,
    gender: "Femenino",
    liters: 1,
    name: "Chanel No. 5",
    perfumeType: "Eau de Parfum",
    price: 100,
    scents: ["Floral", "Aldehydic"],
  },
  {
    id: "4",
    available: true,
    brand: "Chanel",
    cant: 1,
    gender: "Femenino",
    liters: 1,
    name: "Chanel No. 5",
    perfumeType: "Eau de Parfum",
    price: 100,
    scents: ["Floral", "Aldehydic"],
  },
  {
    id: "5",
    available: true,
    brand: "Chanel",
    cant: 1,
    gender: "Femenino",
    liters: 1,
    name: "Chanel No. 5",
    perfumeType: "Eau de Parfum",
    price: 100,
    scents: ["Floral", "Aldehydic"],
  },
  {
    id: "6",
    available: true,
    brand: "Chanel",
    cant: 1,
    gender: "Femenino",
    liters: 1,
    name: "Chanel No. 5",
    perfumeType: "Eau de Parfum",
    price: 100,
    scents: ["Floral", "Aldehydic"],
  },
  {
    id: "7",
    available: true,
    brand: "Chanel",
    cant: 1,
    gender: "Femenino",
    liters: 1,
    name: "Chanel No. 5",
    perfumeType: "Eau de Parfum",
    price: 100,
    scents: ["Floral", "Aldehydic"],
  },
  {
    id: "8",
    available: true,
    brand: "Chanel",
    cant: 1,
    gender: "Femenino",
    liters: 1,
    name: "Chanel No. 5",
    perfumeType: "Eau de Parfum",
    price: 100,
    scents: ["Floral", "Aldehydic"],
  },
  {
    id: "9",
    available: true,
    brand: "Chanel",
    cant: 1,
    gender: "Femenino",
    liters: 1,
    name: "Chanel No. 5",
    perfumeType: "Eau de Parfum",
    price: 100,
    scents: ["Floral", "Aldehydic"],
  },
  {
    id: "10",
    available: true,
    brand: "Chanel",
    cant: 1,
    gender: "Femenino",
    liters: 1,
    name: "Chanel No. 5",
    perfumeType: "Eau de Parfum",
    price: 100,
    scents: ["Floral", "Aldehydic"],
  },
  {
    id: "11",
    available: true,
    brand: "Chanel",
    cant: 1,
    gender: "Femenino",
    liters: 1,
    name: "Chanel No. 5",
    perfumeType: "Eau de Parfum",
    price: 100,
    scents: ["Floral", "Aldehydic"],
  },
  {
    id: "12",
    available: true,
    brand: "Chanel",
    cant: 1,
    gender: "Femenino",
    liters: 1,
    name: "Chanel No. 5",
    perfumeType: "Eau de Parfum",
    price: 100,
    scents: ["Floral", "Aldehydic"],
  },
  {
    id: "13",
    available: true,
    brand: "Chanel",
    cant: 1,
    gender: "Femenino",
    liters: 1,
    name: "Chanel No. 5",
    perfumeType: "Eau de Parfum",
    price: 100,
    scents: ["Floral", "Aldehydic"],
  },
  {
    id: "14",
    available: true,
    brand: "Chanel",
    cant: 1,
    gender: "Femenino",
    liters: 1,
    name: "Chanel No. 5",
    perfumeType: "Eau de Parfum",
    price: 100,
    scents: ["Floral", "Aldehydic"],
  },
  {
    id: "15",
    available: true,
    brand: "Chanel",
    cant: 1,
    gender: "Femenino",
    liters: 1,
    name: "Chanel No. 5",
    perfumeType: "Eau de Parfum",
    price: 100,
    scents: ["Floral", "Aldehydic"],
  },
];

export default function PerfumesPage() {
  return (
    <>
      <PerfumesContainer perfumes={perfumes} />
    </>
  );
}
