name: Deploy to VPS

on:
  workflow_dispatch:
  push:
    branches: [ "dev" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.VPS_SSH_KEY }}
          known_hosts: "github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl"

      - name: Execute Deploy Script
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} "
            cd /home/deployer && 
            git clone git@github.com:the-trident-AAA/perfumery-backoffice.git || true && 
            cd perfumery-backoffice &&
            rm -f .env &&
            echo 'NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}' > .env &&
            echo 'AUTH_SECRET=${{ secrets.AUTH_SECRET }}' >> .env &&
            git pull origin dev && 
            docker-compose down &&
            docker-compose pull && 
            docker-compose up -d --build
          "